### ISSUE TITLE
Umständlicher Programmcode

### ISSUE THREAD

**Issue by Effzumdeh** [Effzumdeh/casestudydhbw#19]
Im bisherigen Backend wird zunächst eine Verbindung zur MariaDB erstellt und anschließend in einem executeUpdate auf die entsprechende Datenbank "fallstudie" referenziert. Aus Gründen verbesserter Laufzeit könnte auch direkt auf fallstudie verbunden werden.'

Danke!

**Comment by FelixAlverum** [comment]
Alles im DatenbankHandler gelöst
